# Generated by Django 3.1 on 2020-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_time', models.TextField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('age', models.ImageField(upload_to='')),
                ('cr_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
