# Generated by Django 3.1 on 2020-09-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='cr_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
